import { requirePrincipal } from '../../auth/principal.ts';
// Rich Academic Curriculum Data: Units, Chapters, Lessons, Takeaways & Practice Questions
import type { CourseUnit, AcademicInstitution } from '../../../src/types/education.ts';

export const DEFAULT_COURSE_UNITS: Record<string, CourseUnit[]> = {
  'class-phys-301': [
    {
      id: 'unit-phys-1',
      courseId: 'class-phys-301',
      number: 1,
      title: 'Foundations of Wave Mechanics & Schrödinger Dynamics',
      description: 'Origins of quantum mechanics, wave-particle duality, state vectors, probability density conservation, and Hermitian operator observables.',
      learningObjectives: [
        'Formulate the time-dependent and time-independent Schrödinger equations.',
        'Derive probability current density and prove conservation of total probability.',
        'Apply boundary conditions to infinite and finite square potential wells.'
      ],
      estimatedHours: 12,
      masteryPercent: 92,
      isCompleted: true,
      lessons: [
        {
          id: 'les-phys-101',
          unitId: 'unit-phys-1',
          courseId: 'class-phys-301',
          number: 1,
          title: 'Schrödinger Wave Equation & Postulates',
          description: 'Historical formulation of the de Broglie hypothesis, wave-packet propagation, and differential wave equation.',
          durationMinutes: 45,
          isCompleted: true,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'The Schrödinger equation i ħ ∂Ψ/∂t = HΨ serves as the fundamental equation of motion in non-relativistic quantum physics. State vectors belong to a complex Hilbert space.',
          keyTakeaways: [
            'State function Ψ(x,t) contains all measurable physical information about the quantum system.',
            'Linear superposition implies interference of probability amplitudes.',
            'Operators corresponding to physical observables must be Hermitian to yield real eigenvalues.'
          ],
          practiceQuestions: [
            {
              id: 'pq-101-1',
              question: 'Why must quantum observable operators be Hermitian?',
              options: [
                'To guarantee that all measurement eigenvalues are strictly real numbers',
                'To ensure wave functions decay to zero at infinity',
                'To prevent magnetic field divergence',
                'To conserve relativistic kinetic energy'
              ],
              correctIndex: 0,
              explanation: 'Hermitian operators (H = H†) have real eigenvalues and orthogonal eigenvectors, ensuring real measurement outcomes.'
            }
          ]
        },
        {
          id: 'les-phys-102',
          unitId: 'unit-phys-1',
          courseId: 'class-phys-301',
          number: 2,
          title: 'Probability Current & Born Rule Continuity',
          description: 'Derivation of the continuity equation ∂ρ/∂t + ∇·J = 0 and probability current vector.',
          durationMinutes: 40,
          isCompleted: true,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'Probability density ρ(x,t) = |Ψ(x,t)|² is conserved under unitary time evolution generated by Hermitian Hamiltonians.',
          keyTakeaways: [
            'Probability current J = (ħ/2mi) [Ψ* ∇Ψ - Ψ ∇Ψ*]',
            'Stationary states have zero net probability flux divergence.',
            'Unitary evolution guarantees total probability ∫|Ψ|² d³x = 1 for all time.'
          ]
        },
        {
          id: 'les-phys-103',
          unitId: 'unit-phys-1',
          courseId: 'class-phys-301',
          number: 3,
          title: 'Hermitian Operators & Quantum Measurements',
          description: 'Measurement postulates, projection operators, commutator relations, and the generalized Heisenberg uncertainty principle.',
          durationMinutes: 50,
          isCompleted: true,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'The commutator [A, B] = AB - BA measures compatibility. Non-commuting observables obey σ_A σ_B ≥ 1/2 |⟨[A,B]⟩|.',
          keyTakeaways: [
            'Canonical commutation relation [x, p] = i ħ',
            'Compatible observables share a simultaneous eigenbasis.',
            'Expectation value ⟨A⟩ = ⟨Ψ|A|Ψ⟩.'
          ]
        }
      ]
    },
    {
      id: 'unit-phys-2',
      courseId: 'class-phys-301',
      number: 2,
      title: 'Quantum Harmonic Oscillators & Ladder Operators',
      description: 'Algebraic solution of the 1D quantum oscillator using lowering (a) and raising (a†) operators, energy eigenvalue spectra, and ground state zero-point fluctuations.',
      learningObjectives: [
        'Define dimensionless position and momentum ladder operators.',
        'Prove the commutation relation [a, a†] = 1.',
        'Derive energy eigenvalues E_n = ħω (n + 1/2) and stationary wavefunctions.',
        'Analyze vacuum zero-point energy and coherent states.'
      ],
      estimatedHours: 16,
      masteryPercent: 78,
      isCompleted: false,
      quizId: 'quiz-seed-phys-1',
      lessons: [
        {
          id: 'les-phys-201',
          unitId: 'unit-phys-2',
          courseId: 'class-phys-301',
          number: 1,
          title: 'Harmonic Hamiltonian & Algebraic Factorization',
          description: 'Recasting the quadratic potential H = p²/2m + 1/2 m ω² x² into dimensionless operator products.',
          durationMinutes: 40,
          isCompleted: true,
          videoId: 'vid-seed-phys-1',
          videoTimestampSeconds: 0,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'By factoring the Hamiltonian H = ħω (a† a + 1/2), we simplify differential equations into algebraic ladder mechanics.',
          keyTakeaways: [
            'Ladder operator a = √(mω/2ħ) (x + i p / mω)',
            'Adjoint operator a† = √(mω/2ħ) (x - i p / mω)',
            'Number operator N = a† a is Hermitian with integer eigenvalues n ≥ 0.'
          ],
          practiceQuestions: [
            {
              id: 'pq-201-1',
              question: 'What is the ground state energy of a 1D quantum harmonic oscillator of frequency ω?',
              options: [
                'E_0 = 0 (zero energy)',
                'E_0 = 1/2 ħ ω (zero-point energy)',
                'E_0 = ħ ω',
                'E_0 = 2 ħ ω'
              ],
              correctIndex: 1,
              explanation: 'Due to the Heisenberg uncertainty principle, quantum ground states retain zero-point fluctuations E_0 = 1/2 ħ ω.'
            }
          ]
        },
        {
          id: 'les-phys-202',
          unitId: 'unit-phys-2',
          courseId: 'class-phys-301',
          number: 2,
          title: 'Creation & Annihilation Operator Algebra',
          description: 'Step-by-step proof of ladder commutator [a, a†] = 1 and derivation of state transitions a|n⟩ = √n |n-1⟩ and a†|n⟩ = √(n+1) |n+1⟩.',
          durationMinutes: 45,
          isCompleted: true,
          videoId: 'vid-seed-phys-1',
          videoTimestampSeconds: 420,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'The ladder action creates and annihilates discrete quanta of energy ħω. The ground state is uniquely annihilated: a|0⟩ = 0.',
          keyTakeaways: [
            '[a, a†] = 1 is the fundamental bosonic commutation relation.',
            'Any excited state |n⟩ can be generated as (a†)ⁿ / √(n!) |0⟩.',
            'Position expectation value ⟨x⟩ and momentum expectation ⟨p⟩ vanish for all energy eigenstates.'
          ]
        },
        {
          id: 'les-phys-203',
          unitId: 'unit-phys-2',
          courseId: 'class-phys-301',
          number: 3,
          title: 'Zero-Point Fluctuations & Vacuum Ground States',
          description: 'Physical implications of the 1/2 ħω vacuum baseline, Casimir effect analogy, and Gaussian ground state wavepackets.',
          durationMinutes: 50,
          isCompleted: false,
          videoId: 'vid-seed-phys-1',
          videoTimestampSeconds: 750,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'Zero-point fluctuations mean a quantum particle in a harmonic potential can never come to rest. The ground state wavefunction is a minimum-uncertainty Gaussian.',
          keyTakeaways: [
            'Ψ_0(x) = (mω/πħ)^(1/4) exp(-mω x² / 2ħ)',
            'Uncertainty product Δx Δp = ħ/2 attains the theoretical minimum bound.',
            'Zero-point fluctuations play a critical role in quantum optics and vacuum field quantization.'
          ],
          practiceQuestions: [
            {
              id: 'pq-203-1',
              question: 'How does the ground state wavefunction Ψ_0(x) behave spatially?',
              options: [
                'It is an asymmetric sinusoidal wave',
                'It is a centered Gaussian wavepacket with no nodes',
                'It is an exponential decay with one zero crossing',
                'It vanishes at the origin'
              ],
              correctIndex: 1,
              explanation: 'The ground state n=0 is an even Gaussian function exp(-mω x² / 2ħ) with zero nodes.'
            }
          ]
        }
      ]
    },
    {
      id: 'unit-phys-3',
      courseId: 'class-phys-301',
      number: 3,
      title: 'Electromagnetic Field Quantization & Dirac Formalism',
      description: 'Second quantization of the electromagnetic field, photon Fock space, vector potentials in Coulomb gauge, and radiation-matter interaction.',
      learningObjectives: [
        'Express vector potential A(r,t) in terms of Fourier normal modes and photon creation/annihilation operators.',
        'Construct multi-photon Fock states |n_k,λ⟩.',
        'Analyze spontaneous emission and dipole radiation transitions.'
      ],
      estimatedHours: 14,
      masteryPercent: 45,
      isCompleted: false,
      lessons: [
        {
          id: 'les-phys-301',
          unitId: 'unit-phys-3',
          courseId: 'class-phys-301',
          number: 1,
          title: 'Vector Potential Normal Mode Expansion',
          description: 'Coulomb gauge condition ∇·A = 0 and harmonic decomposition of the free radiation field in a periodic cavity.',
          durationMinutes: 45,
          isCompleted: false,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'Each radiation mode of wavevector k and polarization λ acts as an independent quantum harmonic oscillator.',
          keyTakeaways: [
            'H_em = ∑_{k,λ} ħ ω_k (a†_{k,λ} a_{k,λ} + 1/2)',
            'Photons are quantized excitations of normal field modes.',
            'Vacuum energy divergence is regularized via normal ordering.'
          ]
        },
        {
          id: 'les-phys-302',
          unitId: 'unit-phys-3',
          courseId: 'class-phys-301',
          number: 2,
          title: 'Photon Fock States & Radiation Transitions',
          description: 'Construction of number states, photon statistics, coherent states vs Fock states, and stimulated vs spontaneous emission.',
          durationMinutes: 50,
          isCompleted: false,
          knowledgeSpaceId: 'ks-quantum',
          notes: 'Spontaneous emission rate is derived via Fermi Golden Rule and quantized vacuum mode interactions.',
          keyTakeaways: [
            'Fock states |n⟩ have definite photon number but completely indeterminate phase.',
            'Coherent states |α⟩ represent classical-like minimum uncertainty laser light.',
            'Einstein A and B coefficients emerge naturally from quantized field operators.'
          ]
        }
      ]
    }
  ],
  'class-math-240': [
    {
      id: 'unit-math-1',
      courseId: 'class-math-240',
      number: 1,
      title: 'Vector Calculus, Gradient, Divergence & Curl',
      description: 'Differential operators in ℝ³, conservative vector fields, line integrals of vector fields, and Green Theorem on the plane.',
      learningObjectives: [
        'Compute gradient ∇f, divergence ∇·F, and curl ∇×F in Cartesian and curvilinear coordinates.',
        'Evaluate line integrals along parameterized curves.',
        'Apply Green Theorem to evaluate circulation and planar flux.'
      ],
      estimatedHours: 10,
      masteryPercent: 88,
      isCompleted: true,
      lessons: [
        {
          id: 'les-math-101',
          unitId: 'unit-math-1',
          courseId: 'class-math-240',
          number: 1,
          title: 'Vector Fields & Differential Operators',
          description: 'Geometric interpretation of scalar gradient, divergence as flux density, and curl as microscopic circulation.',
          durationMinutes: 40,
          isCompleted: true,
          knowledgeSpaceId: 'ks-calculus',
          notes: 'Gradient points in direction of greatest increase; divergence measures field source/sink strength; curl measures rotational vorticity.',
          keyTakeaways: [
            '∇ × (∇ f) = 0 for all C² scalar fields f.',
            '∇ · (∇ × F) = 0 for all C² vector fields F.',
            'Conservative fields have path-independent line integrals.'
          ]
        },
        {
          id: 'les-math-102',
          unitId: 'unit-math-1',
          courseId: 'class-math-240',
          number: 2,
          title: 'Line Integrals & Green Theorem in the Plane',
          description: 'Circulation and flux forms of Green Theorem relating boundary line integrals to 2D double integrals.',
          durationMinutes: 45,
          isCompleted: true,
          knowledgeSpaceId: 'ks-calculus',
          notes: 'Green Theorem states ∮_C (P dx + Q dy) = ∬_D (∂Q/∂x - ∂P/∂y) dA for positively oriented simple closed curves C = ∂D.',
          keyTakeaways: [
            'Relates 1D closed boundary line integral to 2D interior area integral.',
            'Planar area formula Area = 1/2 ∮_C (x dy - y dx).',
            'Fundamental precursor to 3D Stokes and Divergence theorems.'
          ]
        }
      ]
    },
    {
      id: 'unit-math-2',
      courseId: 'class-math-240',
      number: 2,
      title: 'Surface Integrals & Stokes Theorem',
      description: 'Parametric surfaces, orientation, surface curl flux, generalized Stokes Theorem, and exterior differential forms.',
      learningObjectives: [
        'Parameterize 2D surfaces in 3-space and compute normal vectors.',
        'Evaluate flux surface integrals ∬_S F · dS.',
        'Prove and apply classical Stokes Theorem ∬_S (∇ × F) · dS = ∮_{∂S} F · dr.',
        'Unify vector theorems into the exterior derivative form ∫_M dω = ∫_{∂M} ω.'
      ],
      estimatedHours: 14,
      masteryPercent: 75,
      isCompleted: false,
      lessons: [
        {
          id: 'les-math-201',
          unitId: 'unit-math-2',
          courseId: 'class-math-240',
          number: 1,
          title: 'Parametric Surfaces & Normal Flux Integrals',
          description: 'Surface parameterization r(u,v), tangent vectors r_u × r_v, surface element dS, and flux calculations.',
          durationMinutes: 45,
          isCompleted: true,
          videoId: 'vid-seed-math-1',
          videoTimestampSeconds: 0,
          knowledgeSpaceId: 'ks-calculus',
          notes: 'Surface flux represents the net volume rate of vector field flow passing through oriented surface S per unit time.',
          keyTakeaways: [
            'Normal vector n = (r_u × r_v) / |r_u × r_v|',
            'Surface differential dS = (r_u × r_v) du dv',
            'Orientation is fixed by the right-hand rule across the boundary curve.'
          ]
        },
        {
          id: 'les-math-202',
          unitId: 'unit-math-2',
          courseId: 'class-math-240',
          number: 2,
          title: 'Stokes Theorem & Circulation-Flux Duality',
          description: 'Derivation of classical Stokes theorem, topological independence of surface capping, and boundary orientation rules.',
          durationMinutes: 50,
          isCompleted: false,
          videoId: 'vid-seed-math-1',
          videoTimestampSeconds: 240,
          knowledgeSpaceId: 'ks-calculus',
          notes: 'Stokes theorem equates the surface integral of the curl of F across ANY open surface S sharing boundary C to the line integral around C.',
          keyTakeaways: [
            '∬_S (∇ × F) · dS = ∮_{∂S} F · dr',
            'Surface independence: Two different surfaces sharing the exact same boundary curve C yield identical curl flux.',
            'For closed surfaces (∂S = ∅), the total curl flux is identically zero.'
          ],
          practiceQuestions: [
            {
              id: 'pq-202-1',
              question: 'If surface S is a closed sphere (boundary ∂S = ∅), what is ∬_S (∇ × F) · dS?',
              options: [
                '4 π times the radius',
                '0 (identically zero)',
                'Equal to the volume enclosed',
                'Dependent on the vector field curl at the equator'
              ],
              correctIndex: 1,
              explanation: 'Since a closed sphere has no boundary (∂S = ∅), the boundary line integral is 0, so the total curl flux is identically zero.'
            }
          ]
        },
        {
          id: 'les-math-203',
          unitId: 'unit-math-2',
          courseId: 'class-math-240',
          number: 3,
          title: 'Differential Forms & Generalized Stokes Theorem',
          description: 'Differential k-forms, wedge product ∧, exterior derivative d, and the universal theorem ∫_M dω = ∫_{∂M} ω.',
          durationMinutes: 45,
          isCompleted: false,
          knowledgeSpaceId: 'ks-calculus',
          notes: 'Differential forms unify the Fundamental Theorem of Calculus, Green Theorem, Stokes Theorem, and Divergence Theorem into one master formula.',
          keyTakeaways: [
            'Wedge product is alternating: dx ∧ dy = - dy ∧ dx',
            'Nilpotent exterior derivative: d(dω) = 0 for any form ω',
            'Generalized Stokes: ∫_M dω = ∫_{∂M} ω applies in arbitrary dimensions.'
          ]
        }
      ]
    }
  ],
  'class-cs-420': [
    {
      id: 'unit-cs-1',
      courseId: 'class-cs-420',
      number: 1,
      title: 'Transformer Architecture & Attention Mechanisms',
      description: 'Scaled dot-product attention, multi-head projections, positional encoding, and transformer encoder-decoder layers.',
      learningObjectives: [
        'Derive the Attention(Q, K, V) = softmax(Q Kᵀ / √d_k) V matrix operation.',
        'Implement multi-head attention projections.',
        'Analyze computational complexity and context window scaling.'
      ],
      estimatedHours: 12,
      masteryPercent: 60,
      isCompleted: false,
      lessons: [
        {
          id: 'les-cs-101',
          unitId: 'unit-cs-1',
          courseId: 'class-cs-420',
          number: 1,
          title: 'Scaled Dot-Product & Multi-Head Attention',
          description: 'Query, Key, Value tensor transformations and temperature scaling factor 1/√d_k.',
          durationMinutes: 45,
          isCompleted: true,
          notes: 'Attention allows tokens in a sequence to dynamically attend to all other token positions with learned relational weights.',
          keyTakeaways: [
            'Multi-head attention projects queries, keys, and values h times into lower-dimensional subspaces.',
            'Attention matrix softmax normalization ensures row-wise sum equals 1.',
            'Residual connections and layer normalization preserve gradient flow.'
          ]
        },
        {
          id: 'les-cs-102',
          unitId: 'unit-cs-1',
          courseId: 'class-cs-420',
          number: 2,
          title: 'Positional Embeddings & Context Windows',
          description: 'Sinusoidal positional embeddings, rotary position embeddings (RoPE), and long-context inference.',
          durationMinutes: 40,
          isCompleted: false,
          notes: 'Transformers have no inherent sequence order without explicit positional encodings added or applied via rotary matrices.',
          keyTakeaways: [
            'Sinusoidal encodings use fixed frequencies PE(pos, 2i) = sin(pos / 10000^(2i/d)).',
            'RoPE applies complex rotation to query and key vectors to encode relative distances.',
            'FlashAttention optimizes GPU SRAM memory hierarchies for quadratic attention speedups.'
          ]
        }
      ]
    },
    {
      id: 'unit-cs-2',
      courseId: 'class-cs-420',
      number: 2,
      title: 'Autonomous Tool Calling & Multi-Agent Loops',
      description: 'Function calling schemas, sandboxed execution, verification loops, error isolation, and multi-turn agent orchestration.',
      learningObjectives: [
        'Declare OpenAPI compliant JSON schema function definitions.',
        'Implement a sandboxed agent execution loop with retries and fallbacks.',
        'Enforce security barriers and defense against prompt injection.'
      ],
      estimatedHours: 14,
      masteryPercent: 30,
      isCompleted: false,
      lessons: [
        {
          id: 'les-cs-201',
          unitId: 'unit-cs-2',
          courseId: 'class-cs-420',
          number: 1,
          title: 'Function Calling Declarations & Tool Execution',
          description: 'Structured JSON argument validation, schema enforcement, and tool dispatch in LLM pipelines.',
          durationMinutes: 45,
          isCompleted: false,
          notes: 'Tool declarations provide the model with machine-readable interfaces to inspect telemetry, run calculations, or query databases.',
          keyTakeaways: [
            'Schema arguments must be strictly validated before execution.',
            'Tool execution errors should return structured error payloads back to the model rather than crashing.',
            'Stateful sessions require tracking conversation turn history across multiple tool execution cycles.'
          ]
        }
      ]
    }
  ],
  'class-eng-510': [
    {
      id: 'unit-eng-1',
      courseId: 'class-eng-510',
      number: 1,
      title: 'Keplerian Orbital Mechanics & Transfer Trajectories',
      description: 'Two-body gravitational problem, orbital elements, Hohmann transfer orbits, and bi-elliptic maneuvers.',
      learningObjectives: [
        'Calculate specific orbital energy and vis-viva equation v² = μ (2/r - 1/a).',
        'Design Hohmann transfer trajectory delta-v requirements between circular orbits.',
        'Analyze plane change maneuvers and hyperbolic escape trajectories.'
      ],
      estimatedHours: 10,
      masteryPercent: 50,
      isCompleted: false,
      lessons: [
        {
          id: 'les-eng-101',
          unitId: 'unit-eng-1',
          courseId: 'class-eng-510',
          number: 1,
          title: 'Vis-Viva Equation & Conic Orbital Trajectories',
          description: 'Gravitational potential, conservation of angular momentum, and eccentricity vector classification.',
          durationMinutes: 45,
          isCompleted: true,
          notes: 'Specific orbital energy ε = v²/2 - μ/r = -μ/(2a) determines whether an orbit is elliptic, parabolic, or hyperbolic.',
          keyTakeaways: [
            'Vis-viva equation: v = √(μ (2/r - 1/a))',
            'Elliptic orbits have eccentricity 0 ≤ e < 1.',
            'Perigee velocity is maximized; apogee velocity is minimized.'
          ]
        },
        {
          id: 'les-eng-102',
          unitId: 'unit-eng-1',
          courseId: 'class-eng-510',
          number: 2,
          title: 'Hohmann Transfer Delta-V Calculations',
          description: 'Two-impulse coplanar orbital transfer between circular orbits minimizing fuel consumption.',
          durationMinutes: 50,
          isCompleted: false,
          notes: 'A Hohmann transfer employs an intermediate elliptical transfer orbit tangent to both initial and final orbits.',
          keyTakeaways: [
            'Semi-major axis of transfer orbit a_t = (r_1 + r_2) / 2.',
            'Total Δv = |v_t1 - v_1| + |v_2 - v_t2|.',
            'Transfer duration is half the orbital period of the transfer ellipse: t_transfer = π √(a_t³ / μ).'
          ]
        }
      ]
    }
  ]
};

export const DEFAULT_INSTITUTION: AcademicInstitution = {
  id: 'inst-stark-academy',
  name: 'Stark Academy of Science & Advanced Engineering',
  code: 'STARK-ACADEMY',
  campus: 'Stark Industries R&D Campus, Sector 4',
  currentAcademicYear: '2026–2027 (Fall Semester)',
  grades: [
    {
      id: 'grade-12',
      name: 'Grade 12 / Senior Level',
      code: 'G12',
      level: 12,
      classesCount: 4,
      studentsCount: 38
    },
    {
      id: 'grade-11',
      name: 'Grade 11 / Junior Level',
      code: 'G11',
      level: 11,
      classesCount: 3,
      studentsCount: 42
    },
    {
      id: 'grade-grad',
      name: 'Post-Graduate Research Fellow',
      code: 'GRAD',
      level: 13,
      classesCount: 2,
      studentsCount: 16
    }
  ],
  batches: [
    {
      id: 'batch-alpha-26',
      name: 'Alpha Quantum Cohort 2026',
      code: 'BATCH-AQ26',
      gradeId: 'grade-12',
      term: 'Fall 2026',
      studentCount: 20,
      classIds: ['class-phys-301', 'class-math-240']
    },
    {
      id: 'batch-beta-26',
      name: 'Beta Cybernetics Cohort 2026',
      code: 'BATCH-BC26',
      gradeId: 'grade-12',
      term: 'Fall 2026',
      studentCount: 18,
      classIds: ['class-cs-420', 'class-eng-510']
    }
  ]
};
